apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: argo-rbind
  namespace: default
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: AC Access Control
    policy.open-cluster-management.io/controls: AC-3 Access Enforcement
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: argo-admin-bind
        spec:
          remediationAction: inform
          severity: high
          namespaceSelector:
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: RoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: argo-admin-bind
                  namespace: default
                subjects:
                  - name: openshift-gitops-argocd-application-controller
                    namespace: openshift-gitops
                    kind: ServiceAccount
                roleRef:
                  name: admin
                  kind: ClusterRole
                  apiGroup: rbac.authorization.k8s.io
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: argo-acm-admin-bind
        spec:
          remediationAction: inform
          severity: high
          namespaceSelector:
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: RoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: argo-acm-admin-bind
                  namespace: default
                subjects:
                  - name: openshift-gitops-argocd-application-controller
                    namespace: openshift-gitops
                    kind: ServiceAccount
                roleRef:
                  name: open-cluster-management:admin-aggregate
                  kind: ClusterRole
                  apiGroup: rbac.authorization.k8s.io                  
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: argo-rbind-placement
  namespace: default
  labels:
    global-hub.open-cluster-management.io/local-resource: "True"   
spec:
  clusterSelector:
    matchExpressions:
      - key: local-cluster
        operator: In
        values:
          - "true"
  clusterConditions: []
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: argo-rbind-placement
  namespace: default
placementRef:
  name: argo-rbind-placement
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: argo-rbind
    apiGroup: policy.open-cluster-management.io
    kind: Policy
